{% set name = "littletable" %}
{% set version = "2.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/littletable-{{ version }}.tar.gz
  sha256: 2ffb079d6627a51cab87b520a9f5b9048b1484437d6084fd49cdf7b44c332743

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9

    # Not listed as required but package check to see if available
    - numpy
    - lxml
    - openpyxl
    - rich
    - traits

test:
  source_files:
    - ./unit_tests.py
  imports:
    - littletable
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not test_sliced_indexing and not test_csv_compressed_import and not test_csv_filtered_import and not test_excel_export and not test_excel_import and not test_csv_import_source_info and not TableImportExportTests" ./unit_tests.py
  requires:
    - attrs
    - pip
    - pydantic
    - pytest
    - traitlets

about:
  home: https://github.com/ptmcg/littletable/
  summary: Python in-memory ORM database
  doc_url: https://pythonhosted.org/littletable/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
