{% set name = "littletable" %}
{% set version = "2.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/littletable-{{ version }}.tar.gz
  sha256: 7f478decaf4acc28cb3be21b64523b1fd5e999bd35ebbb8b50d58d4888b7c7c9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6.8
  run:
    - python >=3.6.8

test:
  source_files:
    - ./unit_tests.py
  imports:
    - littletable
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys -k "not TableImportExportTests and not test_sliced_indexing" ./unit_tests.py
  requires:
    - openpyxl
    - pip
    - pytest
    - rich

about:
  home: https://github.com/ptmcg/littletable/
  summary: Python in-memory ORM database
  doc_url: https://pythonhosted.org/littletable/
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
